services:
  - type: web
    name: fifa-coins-backend
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        value: your_secret_key_here
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: MONGO_URL
        value: mongodb+srv://fifacoins:Ahmadaagh123@cluster0.8axuigm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
